/**
 * Auto-generated by scripts/generate-herolist.js
 * Source: Tencent LOL Official CDN (gtimg.cn)
 * Total Heroes: 172
 * Generated at: 2026/1/19 06:49:39
 */

export interface Hero { 
  id: string; 
  name: string; 
  nameCn: string; 
  titleCn: string; 
  roles: string[]; 
}

export const RAW_HEROES: Hero[] = [
  {
    "id": "aatrox",
    "name": "Aatrox",
    "nameCn": "亚托克斯",
    "titleCn": "暗裔剑魔",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "ahri",
    "name": "Ahri",
    "nameCn": "阿狸",
    "titleCn": "九尾妖狐",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "akali",
    "name": "Akali",
    "nameCn": "阿卡丽",
    "titleCn": "离群之刺",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "akshan",
    "name": "Akshan",
    "nameCn": "阿克尚",
    "titleCn": "影哨",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "alistar",
    "name": "Alistar",
    "nameCn": "阿利斯塔",
    "titleCn": "牛头酋长",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "ambessa",
    "name": "Ambessa",
    "nameCn": "安蓓萨",
    "titleCn": "铁血狼母",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "amumu",
    "name": "Amumu",
    "nameCn": "阿木木",
    "titleCn": "殇之木乃伊",
    "roles": [
      "SUP",
      "JG"
    ]
  },
  {
    "id": "anivia",
    "name": "Anivia",
    "nameCn": "艾尼维亚",
    "titleCn": "冰晶凤凰",
    "roles": [
      "MID",
      "JG"
    ]
  },
  {
    "id": "annie",
    "name": "Annie",
    "nameCn": "安妮",
    "titleCn": "黑暗之女",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "aphelios",
    "name": "Aphelios",
    "nameCn": "厄斐琉斯",
    "titleCn": "残月之肃",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "ashe",
    "name": "Ashe",
    "nameCn": "艾希",
    "titleCn": "寒冰射手",
    "roles": [
      "BOT",
      "SUP"
    ]
  },
  {
    "id": "aurelionsol",
    "name": "AurelionSol",
    "nameCn": "奥瑞利安索尔",
    "titleCn": "铸星龙王",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "aurora",
    "name": "Aurora",
    "nameCn": "阿萝拉",
    "titleCn": "双界灵兔",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "azir",
    "name": "Azir",
    "nameCn": "阿兹尔",
    "titleCn": "沙漠皇帝",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "bard",
    "name": "Bard",
    "nameCn": "巴德",
    "titleCn": "星界游神",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "belveth",
    "name": "Belveth",
    "nameCn": "卑尔维斯",
    "titleCn": "虚空女皇",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "blitzcrank",
    "name": "Blitzcrank",
    "nameCn": "布里茨",
    "titleCn": "蒸汽机器人",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "brand",
    "name": "Brand",
    "nameCn": "布兰德",
    "titleCn": "复仇焰魂",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "braum",
    "name": "Braum",
    "nameCn": "布隆",
    "titleCn": "弗雷尔卓德之心",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "briar",
    "name": "Briar",
    "nameCn": "贝蕾亚",
    "titleCn": "狂厄蔷薇",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "caitlyn",
    "name": "Caitlyn",
    "nameCn": "凯特琳",
    "titleCn": "皮城女警",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "camille",
    "name": "Camille",
    "nameCn": "卡蜜尔",
    "titleCn": "青钢影",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "cassiopeia",
    "name": "Cassiopeia",
    "nameCn": "卡西奥佩娅",
    "titleCn": "魔蛇之拥",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "chogath",
    "name": "Chogath",
    "nameCn": "科加斯",
    "titleCn": "虚空恐惧",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "corki",
    "name": "Corki",
    "nameCn": "库奇",
    "titleCn": "英勇投弹手",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "darius",
    "name": "Darius",
    "nameCn": "德莱厄斯",
    "titleCn": "诺克萨斯之手",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "diana",
    "name": "Diana",
    "nameCn": "黛安娜",
    "titleCn": "皎月女神",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "draven",
    "name": "Draven",
    "nameCn": "德莱文",
    "titleCn": "荣耀行刑官",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "drmundo",
    "name": "DrMundo",
    "nameCn": "蒙多医生",
    "titleCn": "祖安狂人",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "ekko",
    "name": "Ekko",
    "nameCn": "艾克",
    "titleCn": "时间刺客",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "elise",
    "name": "Elise",
    "nameCn": "伊莉丝",
    "titleCn": "蜘蛛女皇",
    "roles": [
      "MID",
      "JG"
    ]
  },
  {
    "id": "evelynn",
    "name": "Evelynn",
    "nameCn": "伊芙琳",
    "titleCn": "痛苦之拥",
    "roles": [
      "MID",
      "JG"
    ]
  },
  {
    "id": "ezreal",
    "name": "Ezreal",
    "nameCn": "伊泽瑞尔",
    "titleCn": "探险家",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "fiddlesticks",
    "name": "FiddleSticks",
    "nameCn": "费德提克",
    "titleCn": "远古恐惧",
    "roles": [
      "SUP",
      "JG"
    ]
  },
  {
    "id": "fiora",
    "name": "Fiora",
    "nameCn": "菲奥娜",
    "titleCn": "无双剑姬",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "fizz",
    "name": "Fizz",
    "nameCn": "菲兹",
    "titleCn": "潮汐海灵",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "galio",
    "name": "Galio",
    "nameCn": "加里奥",
    "titleCn": "正义巨像",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "gangplank",
    "name": "Gangplank",
    "nameCn": "普朗克",
    "titleCn": "海洋之灾",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "garen",
    "name": "Garen",
    "nameCn": "盖伦",
    "titleCn": "德玛西亚之力",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "gnar",
    "name": "Gnar",
    "nameCn": "纳尔",
    "titleCn": "迷失之牙",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "gragas",
    "name": "Gragas",
    "nameCn": "古拉加斯",
    "titleCn": "酒桶",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "graves",
    "name": "Graves",
    "nameCn": "格雷福斯",
    "titleCn": "法外狂徒",
    "roles": [
      "BOT",
      "JG"
    ]
  },
  {
    "id": "gwen",
    "name": "Gwen",
    "nameCn": "格温",
    "titleCn": "灵罗娃娃",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "hecarim",
    "name": "Hecarim",
    "nameCn": "赫卡里姆",
    "titleCn": "战争之影",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "heimerdinger",
    "name": "Heimerdinger",
    "nameCn": "黑默丁格",
    "titleCn": "大发明家",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "hwei",
    "name": "Hwei",
    "nameCn": "彗",
    "titleCn": "异画师",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "illaoi",
    "name": "Illaoi",
    "nameCn": "俄洛伊",
    "titleCn": "海兽祭司",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "irelia",
    "name": "Irelia",
    "nameCn": "艾瑞莉娅",
    "titleCn": "刀锋舞者",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "ivern",
    "name": "Ivern",
    "nameCn": "艾翁",
    "titleCn": "翠神",
    "roles": [
      "SUP",
      "JG"
    ]
  },
  {
    "id": "janna",
    "name": "Janna",
    "nameCn": "迦娜",
    "titleCn": "风暴之怒",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "jarvaniv",
    "name": "JarvanIV",
    "nameCn": "嘉文四世",
    "titleCn": "德玛西亚皇子",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "jax",
    "name": "Jax",
    "nameCn": "贾克斯",
    "titleCn": "武器大师",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "jayce",
    "name": "Jayce",
    "nameCn": "杰斯",
    "titleCn": "未来守护者",
    "roles": [
      "TOP",
      "BOT"
    ]
  },
  {
    "id": "jhin",
    "name": "Jhin",
    "nameCn": "烬",
    "titleCn": "戏命师",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "jinx",
    "name": "Jinx",
    "nameCn": "金克丝",
    "titleCn": "暴走萝莉",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "kaisa",
    "name": "Kaisa",
    "nameCn": "卡莎",
    "titleCn": "虚空之女",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "kalista",
    "name": "Kalista",
    "nameCn": "卡莉丝塔",
    "titleCn": "复仇之矛",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "karma",
    "name": "Karma",
    "nameCn": "卡尔玛",
    "titleCn": "天启者",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "karthus",
    "name": "Karthus",
    "nameCn": "卡尔萨斯",
    "titleCn": "死亡颂唱者",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "kassadin",
    "name": "Kassadin",
    "nameCn": "卡萨丁",
    "titleCn": "虚空行者",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "katarina",
    "name": "Katarina",
    "nameCn": "卡特琳娜",
    "titleCn": "不祥之刃",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "kayle",
    "name": "Kayle",
    "nameCn": "凯尔",
    "titleCn": "正义天使",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "kayn",
    "name": "Kayn",
    "nameCn": "凯隐",
    "titleCn": "影流之镰",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "kennen",
    "name": "Kennen",
    "nameCn": "凯南",
    "titleCn": "狂暴之心",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "khazix",
    "name": "Khazix",
    "nameCn": "卡兹克",
    "titleCn": "虚空掠夺者",
    "roles": [
      "MID",
      "JG"
    ]
  },
  {
    "id": "kindred",
    "name": "Kindred",
    "nameCn": "千珏",
    "titleCn": "永猎双子",
    "roles": [
      "BOT",
      "JG"
    ]
  },
  {
    "id": "kled",
    "name": "Kled",
    "nameCn": "克烈",
    "titleCn": "暴怒骑士",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "kogmaw",
    "name": "KogMaw",
    "nameCn": "克格莫",
    "titleCn": "深渊巨口",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "ksante",
    "name": "KSante",
    "nameCn": "奎桑提",
    "titleCn": "纳祖芒荣耀",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "leblanc",
    "name": "Leblanc",
    "nameCn": "乐芙兰",
    "titleCn": "诡术妖姬",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "leesin",
    "name": "LeeSin",
    "nameCn": "李青",
    "titleCn": "盲僧",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "leona",
    "name": "Leona",
    "nameCn": "蕾欧娜",
    "titleCn": "曙光女神",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "lillia",
    "name": "Lillia",
    "nameCn": "莉莉娅",
    "titleCn": "含羞蓓蕾",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "lissandra",
    "name": "Lissandra",
    "nameCn": "丽桑卓",
    "titleCn": "冰霜女巫",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "lucian",
    "name": "Lucian",
    "nameCn": "卢锡安",
    "titleCn": "圣枪游侠",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "lulu",
    "name": "Lulu",
    "nameCn": "璐璐",
    "titleCn": "仙灵女巫",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "lux",
    "name": "Lux",
    "nameCn": "拉克丝",
    "titleCn": "光辉女郎",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "malphite",
    "name": "Malphite",
    "nameCn": "墨菲特",
    "titleCn": "熔岩巨兽",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "malzahar",
    "name": "Malzahar",
    "nameCn": "玛尔扎哈",
    "titleCn": "虚空先知",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "maokai",
    "name": "Maokai",
    "nameCn": "茂凯",
    "titleCn": "扭曲树精",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "masteryi",
    "name": "MasterYi",
    "nameCn": "易",
    "titleCn": "无极剑圣",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "mel",
    "name": "Mel",
    "nameCn": "梅尔",
    "titleCn": "流光镜影",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "milio",
    "name": "Milio",
    "nameCn": "米利欧",
    "titleCn": "明烛",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "missfortune",
    "name": "MissFortune",
    "nameCn": "厄运小姐",
    "titleCn": "赏金猎人",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "monkeyking",
    "name": "MonkeyKing",
    "nameCn": "孙悟空",
    "titleCn": "齐天大圣",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "mordekaiser",
    "name": "Mordekaiser",
    "nameCn": "莫德凯撒",
    "titleCn": "铁铠冥魂",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "morgana",
    "name": "Morgana",
    "nameCn": "莫甘娜",
    "titleCn": "堕落天使",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "naafiri",
    "name": "Naafiri",
    "nameCn": "纳亚菲利",
    "titleCn": "百裂冥犬",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "nami",
    "name": "Nami",
    "nameCn": "娜美",
    "titleCn": "唤潮鲛姬",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "nasus",
    "name": "Nasus",
    "nameCn": "内瑟斯",
    "titleCn": "沙漠死神",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "nautilus",
    "name": "Nautilus",
    "nameCn": "诺提勒斯",
    "titleCn": "深海泰坦",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "neeko",
    "name": "Neeko",
    "nameCn": "妮蔻",
    "titleCn": "万花通灵",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "nidalee",
    "name": "Nidalee",
    "nameCn": "奈德丽",
    "titleCn": "狂野女猎手",
    "roles": [
      "MID",
      "JG"
    ]
  },
  {
    "id": "nilah",
    "name": "Nilah",
    "nameCn": "尼菈",
    "titleCn": "不羁之悦",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "nocturne",
    "name": "Nocturne",
    "nameCn": "魔腾",
    "titleCn": "永恒梦魇",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "nunu",
    "name": "Nunu",
    "nameCn": "努努和威朗普",
    "titleCn": "雪原双子",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "olaf",
    "name": "Olaf",
    "nameCn": "奥拉夫",
    "titleCn": "狂战士",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "orianna",
    "name": "Orianna",
    "nameCn": "奥莉安娜",
    "titleCn": "发条魔灵",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "ornn",
    "name": "Ornn",
    "nameCn": "奥恩",
    "titleCn": "山隐之焰",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "pantheon",
    "name": "Pantheon",
    "nameCn": "潘森",
    "titleCn": "不屈之枪",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "poppy",
    "name": "Poppy",
    "nameCn": "波比",
    "titleCn": "圣锤之毅",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "pyke",
    "name": "Pyke",
    "nameCn": "派克",
    "titleCn": "血港鬼影",
    "roles": [
      "MID",
      "SUP"
    ]
  },
  {
    "id": "qiyana",
    "name": "Qiyana",
    "nameCn": "奇亚娜",
    "titleCn": "元素女皇",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "quinn",
    "name": "Quinn",
    "nameCn": "奎因",
    "titleCn": "德玛西亚之翼",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "rakan",
    "name": "Rakan",
    "nameCn": "洛",
    "titleCn": "幻翎",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "rammus",
    "name": "Rammus",
    "nameCn": "拉莫斯",
    "titleCn": "披甲龙龟",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "reksai",
    "name": "RekSai",
    "nameCn": "雷克塞",
    "titleCn": "虚空遁地兽",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "rell",
    "name": "Rell",
    "nameCn": "芮尔",
    "titleCn": "镕铁少女",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "renata",
    "name": "Renata",
    "nameCn": "烈娜塔 · 戈拉斯克",
    "titleCn": "炼金男爵",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "renekton",
    "name": "Renekton",
    "nameCn": "雷克顿",
    "titleCn": "荒漠屠夫",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "rengar",
    "name": "Rengar",
    "nameCn": "雷恩加尔",
    "titleCn": "傲之追猎者",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "riven",
    "name": "Riven",
    "nameCn": "锐雯",
    "titleCn": "放逐之刃",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "rumble",
    "name": "Rumble",
    "nameCn": "兰博",
    "titleCn": "机械公敌",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "ryze",
    "name": "Ryze",
    "nameCn": "瑞兹",
    "titleCn": "符文法师",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "samira",
    "name": "Samira",
    "nameCn": "莎弥拉",
    "titleCn": "沙漠玫瑰",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "sejuani",
    "name": "Sejuani",
    "nameCn": "瑟庄妮",
    "titleCn": "北地之怒",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "senna",
    "name": "Senna",
    "nameCn": "赛娜",
    "titleCn": "涤魂圣枪",
    "roles": [
      "BOT",
      "SUP"
    ]
  },
  {
    "id": "seraphine",
    "name": "Seraphine",
    "nameCn": "萨勒芬妮",
    "titleCn": "星籁歌姬",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "sett",
    "name": "Sett",
    "nameCn": "瑟提",
    "titleCn": "腕豪",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "shaco",
    "name": "Shaco",
    "nameCn": "萨科",
    "titleCn": "恶魔小丑",
    "roles": [
      "MID",
      "JG"
    ]
  },
  {
    "id": "shen",
    "name": "Shen",
    "nameCn": "慎",
    "titleCn": "暮光之眼",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "shyvana",
    "name": "Shyvana",
    "nameCn": "希瓦娜",
    "titleCn": "龙血武姬",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "singed",
    "name": "Singed",
    "nameCn": "辛吉德",
    "titleCn": "炼金术士",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "sion",
    "name": "Sion",
    "nameCn": "赛恩",
    "titleCn": "亡灵战神",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "sivir",
    "name": "Sivir",
    "nameCn": "希维尔",
    "titleCn": "战争女神",
    "roles": [
      "BOT",
      "JG"
    ]
  },
  {
    "id": "skarner",
    "name": "Skarner",
    "nameCn": "斯卡纳",
    "titleCn": "上古领主",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "smolder",
    "name": "Smolder",
    "nameCn": "斯莫德",
    "titleCn": "炽炎雏龙",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "sona",
    "name": "Sona",
    "nameCn": "娑娜",
    "titleCn": "琴瑟仙女",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "soraka",
    "name": "Soraka",
    "nameCn": "索拉卡",
    "titleCn": "众星之子",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "swain",
    "name": "Swain",
    "nameCn": "斯维因",
    "titleCn": "诺克萨斯统领",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "sylas",
    "name": "Sylas",
    "nameCn": "塞拉斯",
    "titleCn": "解脱者",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "syndra",
    "name": "Syndra",
    "nameCn": "辛德拉",
    "titleCn": "暗黑元首",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "tahmkench",
    "name": "TahmKench",
    "nameCn": "塔姆",
    "titleCn": "河流之王",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "taliyah",
    "name": "Taliyah",
    "nameCn": "塔莉垭",
    "titleCn": "岩雀",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "talon",
    "name": "Talon",
    "nameCn": "泰隆",
    "titleCn": "刀锋之影",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "taric",
    "name": "Taric",
    "nameCn": "塔里克",
    "titleCn": "瓦洛兰之盾",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "teemo",
    "name": "Teemo",
    "nameCn": "提莫",
    "titleCn": "迅捷斥候",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "thresh",
    "name": "Thresh",
    "nameCn": "锤石",
    "titleCn": "魂锁典狱长",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "tristana",
    "name": "Tristana",
    "nameCn": "崔丝塔娜",
    "titleCn": "麦林炮手",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "trundle",
    "name": "Trundle",
    "nameCn": "特朗德尔",
    "titleCn": "巨魔之王",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "tryndamere",
    "name": "Tryndamere",
    "nameCn": "泰达米尔",
    "titleCn": "蛮族之王",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "twistedfate",
    "name": "TwistedFate",
    "nameCn": "崔斯特",
    "titleCn": "卡牌大师",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "twitch",
    "name": "Twitch",
    "nameCn": "图奇",
    "titleCn": "瘟疫之源",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "udyr",
    "name": "Udyr",
    "nameCn": "乌迪尔",
    "titleCn": "兽灵行者",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "urgot",
    "name": "Urgot",
    "nameCn": "厄加特",
    "titleCn": "无畏战车",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "varus",
    "name": "Varus",
    "nameCn": "韦鲁斯",
    "titleCn": "惩戒之箭",
    "roles": [
      "MID",
      "BOT"
    ]
  },
  {
    "id": "vayne",
    "name": "Vayne",
    "nameCn": "薇恩",
    "titleCn": "暗夜猎手",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "veigar",
    "name": "Veigar",
    "nameCn": "维迦",
    "titleCn": "邪恶小法师",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "velkoz",
    "name": "Velkoz",
    "nameCn": "维克兹",
    "titleCn": "虚空之眼",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "vex",
    "name": "Vex",
    "nameCn": "薇古丝",
    "titleCn": "愁云使者",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "vi",
    "name": "Vi",
    "nameCn": "蔚",
    "titleCn": "皮城执法官",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "viego",
    "name": "Viego",
    "nameCn": "佛耶戈",
    "titleCn": "破败之王",
    "roles": [
      "TOP",
      "MID",
      "JG"
    ]
  },
  {
    "id": "viktor",
    "name": "Viktor",
    "nameCn": "维克托",
    "titleCn": "奥术先驱",
    "roles": [
      "MID",
      "JG"
    ]
  },
  {
    "id": "vladimir",
    "name": "Vladimir",
    "nameCn": "弗拉基米尔",
    "titleCn": "猩红收割者",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "volibear",
    "name": "Volibear",
    "nameCn": "沃利贝尔",
    "titleCn": "不灭狂雷",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "warwick",
    "name": "Warwick",
    "nameCn": "沃里克",
    "titleCn": "祖安怒兽",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "xayah",
    "name": "Xayah",
    "nameCn": "霞",
    "titleCn": "逆羽",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "xerath",
    "name": "Xerath",
    "nameCn": "泽拉斯",
    "titleCn": "远古巫灵",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "xinzhao",
    "name": "XinZhao",
    "nameCn": "赵信",
    "titleCn": "德邦总管",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "yasuo",
    "name": "Yasuo",
    "nameCn": "亚索",
    "titleCn": "疾风剑豪",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "yone",
    "name": "Yone",
    "nameCn": "永恩",
    "titleCn": "封魔剑魂",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "yorick",
    "name": "Yorick",
    "nameCn": "约里克",
    "titleCn": "牧魂人",
    "roles": [
      "TOP"
    ]
  },
  {
    "id": "yunara",
    "name": "Yunara",
    "nameCn": "芸阿娜",
    "titleCn": "不破之誓",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "yuumi",
    "name": "Yuumi",
    "nameCn": "悠米",
    "titleCn": "魔法猫咪",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "zaahen",
    "name": "Zaahen",
    "nameCn": "亚恒",
    "titleCn": "不落魔锋",
    "roles": [
      "TOP",
      "MID"
    ]
  },
  {
    "id": "zac",
    "name": "Zac",
    "nameCn": "扎克",
    "titleCn": "生化魔人",
    "roles": [
      "TOP",
      "JG"
    ]
  },
  {
    "id": "zed",
    "name": "Zed",
    "nameCn": "劫",
    "titleCn": "影流之主",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "zeri",
    "name": "Zeri",
    "nameCn": "泽丽",
    "titleCn": "祖安花火",
    "roles": [
      "BOT"
    ]
  },
  {
    "id": "ziggs",
    "name": "Ziggs",
    "nameCn": "吉格斯",
    "titleCn": "爆破鬼才",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "zilean",
    "name": "Zilean",
    "nameCn": "基兰",
    "titleCn": "时光守护者",
    "roles": [
      "SUP"
    ]
  },
  {
    "id": "zoe",
    "name": "Zoe",
    "nameCn": "佐伊",
    "titleCn": "暮光星灵",
    "roles": [
      "MID"
    ]
  },
  {
    "id": "zyra",
    "name": "Zyra",
    "nameCn": "婕拉",
    "titleCn": "荆棘之兴",
    "roles": [
      "SUP"
    ]
  }
];